title: jekyll-rtd-theme
lang: en-US
description: Just another documentation theme compatible with GitHub Pages, based on sphinx_rtd_theme

edit: true

copyright:
  revision: true
  
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
  
addons:
  - github
  - gems
  - analytics

addons_commit: true

theme: null

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - ci.sh
  - CODE_OF_CONDUCT.md
  - LICENSE
  - jekyll-rtd-theme.gemspec
